name: Lint YML Files

on:
  pull_request:
    paths:
      - 'oss-taxonomy/**/*.yml'
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Run YML linting
        run: bundle exec ruby ./lint_yml_files.rb
