name: Test

on:
  pull_request:
    paths:
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'scripts/**/*.rb'
      - 'test/**/*.rb'
      - '.github/workflows/test.yml'
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Run tests
        run: bundle exec ruby -Itest test/external_sources_test.rb
